application: contactus-form
version: 1
runtime: php
api_version: 1

handlers:

- url: /css
  static_dir: css
  secure: always

- url: /images
  static_dir: images
  secure: always

- url: /js
  static_dir: js
  secure: always

- url: /json
  static_dir: json
  secure: always

- url: /
  script: index.html
  secure: always

